apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
auth:
  secretStore: secretstore   
spec:
  type: pubsub.azure.servicebus  
  metadata:
    - name: connectionString
      value:
      secretKeyRef: 
        name: azure:servicebus